### ISSUE TITLE
Implement a player check before shutting down

### ISSUE THREAD

**Issue by Romanmir** [Gamealition/ForgeAutoShutdown#3]
I'd like to request an enhancement where it simply waits until a few minutes after everyone logs out.

Maybe it will automatically check to see if players are logged in and postpone the shutdown by one hour or some configurable amount. Maybe it checks 15 minutes before the next scheduled time. 

Maybe it uses the whitelist as a way to avoid the occaisional 'fakeplayer' that some mods implement (BC, i think.)

**Comment by RoyCurtis** [comment]
Acknowledged; interesting idea. I could implement it so that it waits a minimum of 24 hours (configurable), then use your idea to check a configured interval for players and shut down at the earliest convenience (when empty).

I'd use a blacklist for fake players; though I wonder if Forge has an API for determining if an entity is indeed a fake player (as long as mods do not work around it, or use something else). I could also probably find a reliable way of making that determination.

Thanks!

**Comment by RoyCurtis** [comment]
@Romanmir - Sorry for the delay in implementing this. This feature is now available in [release 1.0.6](https://github.com/Gamealition/ForgeAutoShutdown/releases/tag/1.0.6).

I implemented it so that, come the scheduled time, it will check for real players on the server. If any are present, it will delay by a set amount of minutes (e.g. 60 - for an hour) and then check again.

When checking, if the server is empty, it will then begin the 5 minute warning if `scheduleWarning` is true, else it will immediately shut down the server.

Hope this helps; please enjoy
